[project]
name = "cpfcluster"
version = "0.1.0"
description = "Component-wise Peak-Finding clustering algorithm"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "umap-learn>=0.5.5",
    "faiss-cpu",
    "numba>=0.58",
    "llvmlite>=0.41",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]
